Encoding:
  Enabled: false
IfUnlessModifier:
  Enabled: false
# Avoid Perl-style regex back references.
AvoidPerlBackrefs:
  Enabled: false
VariableInterpolation:
  Enabled: false
Semicolon:
  AllowBeforeEndInOneLineMethods: false
AsciiComments:
  Enabled: false
AvoidGlobalVars:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AccessorMethodName:
  Enabled: false
LineLength:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
inherit_from: rubocop-todo.yml
inherit_from: rubocop_todo.yml
inherit_from: .rubocop_todo.yml
