default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lancher_es_development
test:
  <<: *default
  database: lancher_es_test

production:
  <<: *default
  database: lancher_es_production
  username: lancher_es
  password: <%= ENV['LANCHER_ES_DATABASE_PASSWORD'] %>
